version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  gnu-complexity:
    enabled: true
exclude_patterns:
- "html5-client/deps/js/*"
- "*deps/*"
